apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaghetti-deployment
  namespace: question-15
  labels:
    app: spaghetti
spec:
  replicas: 7
  selector:
    matchLabels:
      app: pasta
  template:
    metadata:
      labels:
        app: pasta
    spec:
      containers:
      - name: pasta
        image: r.deso.tech/whoami/whoami:latest
      ports:
      - containerPort: 80