apiVersion: betav1applicationcontroller/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: question-06
  labels:
    app: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: whoami
        image: r.deso.tech/whoami/whoami:0.4
        ports:
        - containerPort: 80