apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: foo-app-role
  namespace: question-17
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
