apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-app
  namespace: question-02
  labels:
    app: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo-c01
        image: r.deso.tech/dockerhub/bitnami/kubectl:1.24
        command:
        - sh
        - -c
        - 'while : ; do kubectl get deployments.app ; sleep 3 ; done'