apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-foo
  namespace: question-02
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: foo-app-role
subjects:
- kind: ServiceAccount
  name: foo-app-saccount
  namespace: question-02
