apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-api-deployment
  namespace: question-19
  labels:
    app: manager-api-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      id: manager-api-pod
  template:
    metadata:
      labels:
        id: manager-api-pod
    spec:
      containers:
      - name: manager-container
        image: r.deso.tech/dockerhub/library/nginx:stable
        ports:
          containerPort: 80