apiVersion: v1
kind: Service
metadata:
  labels:
    app: manager-api-svc
  name: manager-api-svc
  namespace: question-19
spec:
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 80
  selector:
    id: manager-api-deployment
  sessionAffinity: None
  type: ClusterIP
