apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccer-deployment
  namespace: question-09
  labels:
    app: soccer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soccer
  template:
    metadata:
      labels:
        app: soccer
    spec:
      containers:
      - name: kubectl
        image: r.deso.tech/dsk/dsutils:latest