apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-deployment
  namespace: question-02
  labels:
    app: pizza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
      - name: kubectl
        image: r.deso.tech/dockerhub/bitnami/kubectl:1.24
        ports:
        - containerPort: 80
      servicaAccountName: default