apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-deployment
  namespace: question-02
  labels:
    app: pizza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
      - name: kubectl
        image: r.deso.tech/dockerhub/bitnami/kubectl:1.24
        command:
        - sh
        - -c
        - while : ; do kubectl get deployments.app ; sleep 3 ; done
      servicaAccountName: default