apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pizza
  namespace: question-02
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pizza
subjects:
- kind: ServiceAccount
  name: pizza
  namespace: question-02
