apiVersion: apps/v1
kind: Deployment
metadata:
  name: macaron-nosql
  namespace: question-13
  labels:
    app: donut
spec:
  replicas: 4
  selector:
    matchLabels:
      app: donut
  template:
    metadata:
      labels:
        app: donut
    spec:
      containers:
      - name: kubectl
        image: r.deso.tech/whoami/whoami:latest