apiVersion: apps/v1
kind: Deployment
metadata:
  name: macaron-nosql
  namespace: question-13
  labels:
    app: macaron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: macaron
  template:
    metadata:
      labels:
        app: macaron
    spec:
      containers:
      - name: macaron
        image: r.deso.tech/whoami/whoami:latest